<table border="1" width="100%" bordercolorlight="#000000" cellspacing="0" cellpadding="0">
<br>
	<caption><p><b><font size="4">领照清单</font></b></p>
	<p align="left" style="line-height: 150%">
	<font face="仿宋_GBK" style="font-size: 11pt">注：领照人应为<%=lzrtitle %>或其授权人。</font></p></caption>
	<tr>
		<td height="40" align="center" >注册号</td>
		<td align="center"  >　</td>
		<td align="center"  >核准日期</td>
		<td align="center"  >　</td>
		<td align="center"  >打印人</td>
		<td align="center" width="10%">  </td>
	</tr>
	<tr>
		<td   height="40" align="center" >营业执照编号</td>
		<td  colspan="5" height="40">
		<p align="left">正本：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
		副本1：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
		副本2：</td>
	</tr>
	<tr>
		<td   height="40" align="center" >缴费数额</td>
		<td width="27%"  colspan="2" height="40" align="center" >　</td>
		<td height="40" align="center" >缴费收据号</td>
		<td colspan="2" height="40" align="center">　</td>
	</tr>
	<tr>
		<td   rowspan="4" height="40" align="center" >
		领<br>
		照<br>
		人</td>
		<td  height="40" align="center" >签&nbsp;&nbsp;&nbsp; 字</td>
		<td  colspan="4" height="40" align="center" >　</td>
	</tr>
	<tr>
		<td  height="40" align="center" >日&nbsp;&nbsp;&nbsp; 期</td>
		<td  colspan="4" height="40" align="center" >　</td>
	</tr>
	<tr>
		<td  height="40" align="center" >证件名称</td>
		<td  colspan="4" height="40" align="center" >　</td>
	</tr>
	<tr>
		<td  height="40" align="center" >证件号码</td>
		<td  colspan="4" height="40" align="center" >　</td>
	</tr>
	<tr>
		<td   rowspan="2" height="40" align="center" >发 照 人</td>
		<td  height="40" align="center" >签&nbsp;&nbsp;&nbsp; 字</td>
		<td  colspan="4" height="40" align="center" >　</td>
	</tr>
	<tr>
		<td  height="40" align="center" >日&nbsp;&nbsp;&nbsp; 期</td>
		<td  colspan="4" height="40" align="center" >　</td>
	</tr>
	<tr>
		<td   height="40" align="center" >备&nbsp;&nbsp;&nbsp; 注</td>
		<td  height="40" colspan="5" align="center" >　</td>
	</tr>
</table>
<table border="1" width="100%" bordercolor="#000000" cellspacing="0" cellpadding="0">
<p>　</p>
<p>　</p>
<caption>
<b><font size="4">归档情况</font></b>
</caption>
	<tr>
		<td height="40" align="center"  >送 档 人</td>
		<td height="40" width="478" >　</td>
	</tr>
	<tr>
		<td height="40" align="center"  >接 档 人</td>
		<td height="40" width="478" >　</td>
	</tr>
	<tr>
		<td height="40" align="center"  >送档日期</td>
		<td height="40" width="478" >　</td>
	</tr>
	<tr>
		<td height="40" align="center"  >备&nbsp;&nbsp;&nbsp; 注</td>
		<td height="40" width="478" >　</td>
	</tr>
</table>