<table width="100%" border=1 cellpadding="0" cellspacing="0">
<tr>
    <td class="yxsm" colspan="5">&nbsp;注销信息</td> 
</tr>
<tr>
    <td class="lc1" align="center" nowrap="nowrap" width="10%">申请注销<br>登 记 的<br>原   因</td>
    <td class="lc2" colspan=4>
	  <input type="radio" name="CANREA" value="20" checked>投资人决定解散；<br/>
		<input type="radio" name="CANREA" value="83">投资人死亡或者被宣告死亡，无继承人或者继承人决定放弃继承；<br/>
		<input type="radio" name="CANREA" value="50">依法被吊销营业执照；<br/>
		<input type="radio" name="CANREA" value="90">法律、行政法规规定的其他原因：<br/>
   </td>
</tr>
<tr>
   <td class="lc1" colspan="2" align="center" nowrap="nowrap" width="15%">分支机构情况</td>
   <td class="lc2" colspan='3'>
      <input type="radio" checked name="CANCELBRSIGN" size="20" value='1' title='已办理完毕'>已办理完毕 <input type="radio" name="CANCELBRSIGN" size="20" title='无分支机构' value='2' >无分支机构
   </td>
</tr>
<tr>
   <td class="lc1" align="center">清税情况</td>
   <td class="lc2" colspan="4">
      <select id="CLEANTAX" name="CLEANTAX" disblank title="清税情况">
       <option value=''></option>
     <option value='10'>已经清理完毕</option>
	 <option value='30'>未涉及纳税义务</option>
      </select>
   </td>
</tr>
<!-- tr>
    <td class="lc1" align="center">公章缴销枚数</td>
    <td class="lc2" colspan=4>
       <input type="text" name="CAREVNUM" size="10" title="公章缴销枚数" maxlength=3 datatype=num>
    </td>
</tr--> 
</table>