<table border="1" width="100%" >
<caption>公司备案登记事项</caption>
<tr>
	<td class="yxsm" align="center" colspan="2">项目</td>
	<td class="yxsm" align="center">申请备案事项</td>
</tr>
<tr>	
	<td class='lc1'><input name="ALTITEM" value="70" type="checkbox" ></td>
	<td class='lc1'>董事</td>
	<td class='lc2'colspan="2"><font color=red>董事变更请选择变更事项，保存后填写“主要人员”信息！</font>
	<input type="hidden" name="ALTBE70">
	<input type="hidden" name="ALTAF70"></td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="71" type="checkbox" > </td>
	<td class='lc1'>监事</td>
	<td class='lc2'colspan="2"><font color=red>监事变更请选择变更事项，保存后填写“主要人员”信息！</font>
	<input type="hidden" name="ALTBE71">
	<input type="hidden" name="ALTAF71"></td> 
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="72" type="checkbox" ></td>
	<td class='lc1'>经理</td>
	<td class='lc2'colspan="2"><font color=red>经理变更请选择变更事项，保存后填写“主要人员”信息！ </font>
	<input type="hidden" name="ALTBE72">
	<input type="hidden" name="ALTAF72"></td> 
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="73" type="checkbox" > </td>
	<td class='lc1'>章程</td>
	<td class='lc2'><font color=red>章程备案请选中该备案项目后保存！</font>
	<input type="hidden" name="ALTBE73"  maxlength='500'>
	<input type="hidden" name="ALTAF73"  maxlength='500'></td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="74" type="checkbox" ></td>
	<td class='lc1'>章程修正案</td>
	<td class='lc2'><font color=red>章程修正案备案请选中该备案项目后保存！</font>
	<input type="hidden" name="ALTBE74"  maxlength='500'>
	<input type="hidden" name="ALTAF74"  maxlength='500'></td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="79" type="checkbox" ></td>
	<td class='lc1'>清算组成员</td>
	<td class='lc2'>
	<input type="hidden" name="ALTBE79"  maxlength='50'>
	<input type="text" size="50" name="ALTAF79"  maxlength='50' title="清算组成员备案后内容" size="40"></td> 
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="84" type="checkbox" ></td>
	<td class='lc1'>清算组负责人</td>
	<td class='lc2'>
	<input type="hidden" name="ALTBE84"  maxlength='50'>
	<input type="text" size="50" name="ALTAF84"  maxlength='20' title="清算组负责人备案后内容" size="40"></td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="86" type="checkbox" ></td>
	<td class='lc1'>清算组负责人通信地址</td>
	<td class='lc2'>
	<input type="hidden" name="ALTBE86"  maxlength='50'>
	<input type="text" size="50" name="ALTAF86"  maxlength='50' title="清算组负责人通信地址备案后内容" size="40"></td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="87" type="checkbox" ></td>
	<td class='lc1'>清算组负责人电话</td>
	<td class='lc2'>
	<input type="hidden" name="ALTBE87"  maxlength='50'>
	<input type="text" size="50" name="ALTAF87"  maxlength='20' title="清算组负责人电话备案后内容" datatype=int size="40"></td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="81" type="checkbox" ></td>
	<td class='lc1'>分公司增加</td>
	<td class='lc2'colspan="2"><font color=red>分公司增加后请选择变更事项，保存后填写“分支机构”信息！</font>
	<input type="hidden" name="ALTBE81"  maxlength='500'>
	<input type="hidden" name="ALTAF81"  maxlength='500'></td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="82" type="checkbox" ></td>
	<td class='lc1'>分公司变更</td>
	<td class='lc2'colspan="2"><font color=red>分公司变更后请选择变更事项，保存后填写“分支机构”信息！</font>
	<input type="hidden" name="ALTBE82"  maxlength='500'>
	<input type="hidden" name="ALTAF82"  maxlength='500'></td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="83" type="checkbox" ></td>
	<td class='lc1'>分公司注销</td>
	<td class='lc2'colspan="2"><font color=red>分公司注销后请选择变更事项，保存后填写“分支机构”信息！</font>
	<input type="hidden" name="ALTBE83"  maxlength='500'>
	<input type="hidden" name="ALTAF83"  maxlength='500'></td>
</tr>
</table>