<table border="1" width="100%" >
<caption>非公司企业法人备案登记事项</caption>
<tr>
	<td class="yxsm" align="center" colspan="2">项目</td>
	<td class="yxsm" align="center">申请备案事项</td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="55" type="checkbox" onclick="setvalue(this)" ></td>
	<td class='lc1'>主管部门(出资人)名称</td>
	<td class='lc2'><font color=red>主管部门(出资人)名称请选择变更事项，保存后填写“股东或投资信息”信息！</font>
	<input type="hidden" name="ALTBE55"  maxlength='500'>
	<input type="hidden" name="ALTAF55"  maxlength='500'></td> 
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="56" type="checkbox" onclick="setvalue(this)" > </td>
	<td class='lc1'>主管部门(出资人)法人类型</td>
	<td class='lc2'><font color=red>主管部门(出资人)法人类型请选择变更事项，保存后填写“股东或投资信息”信息！</font>
	<input type="hidden" name="ALTBE56"  maxlength='500'>
	<input type="hidden" name="ALTAF56"  maxlength='500'></td> 
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="57" type="checkbox" onclick="setvalue(this)" ></td>
	<td class='lc1'>主管部门(出资人)登记机关</td>
	<td class='lc2'><font color=red>主管部门(出资人)登记机关请选择变更事项，保存后填写“股东或投资信息”信息！</font>
	<input type="hidden" name="ALTBE57"  maxlength='500'>
	<input type="hidden" name="ALTAF57"  maxlength='500'></td> 
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="58" type="checkbox" onclick="setvalue(this)"> </td>
	<td class='lc1'>主管部门(出资人)证照号码</td>
	<td class='lc2'><font color=red>主管部门(出资人)证照号码请选择变更事项，保存后填写“股东或投资信息”信息！</font>
	<input type="hidden" name="ALTBE58"  maxlength='500'>
	<input type="hidden" name="ALTAF58"  maxlength='500'></td> 
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="73" type="checkbox" onclick="setvalue(this)"> </td>
	<td class='lc1'>章程</td>
	<td class='lc2'><font color=red>章程备案请选中该备案项目后保存！</font>
	<input type="hidden" name="ALTBE73"  maxlength='50'>
	<input type="hidden" name="ALTAF73"  maxlength='50'></td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="74" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>章程修正案</td>
	<td class='lc2'><font color=red>章程修正案备案请选中该备案项目后保存！</font>
	<input type="hidden" name="ALTBE74"  maxlength='50'>
	<input type="hidden" name="ALTAF74"  maxlength='50'></td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="790" type="checkbox" ></td>
	<td class='lc1'>财务负责人</td>
	<td class='lc2'colspan="2"><font color=red>请选择变更事项，保存后填写财务负责人信息！</font>
	<input type="hidden" name="ALTBE790"  maxlength='500'>
	<input type="hidden" name="ALTAF790"  maxlength='500'></td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="780" type="checkbox" ></td>
	<td class='lc1'>联络员</td>
	<td class='lc2'colspan="2"><font color=red>请选择变更事项，保存后填写联络员信息！</font>
	<input type="hidden" name="ALTBE780"  maxlength='500'>
	<input type="hidden" name="ALTAF780"  maxlength='500'></td>
</tr>
</table>