<table border="1" width="100%" >
<caption>外国(地区)企业常驻代表机构备案登记事项</caption>
<tr>
	<td class="yxsm" align="center" colspan="2">项目</td>
	<td class="yxsm" align="center">原事项</td>
	<td class="yxsm" align="center">申请备案事项</td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="90" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1' nowrap="nowrap">外国（地区）企业有权签字人姓名</td>
	<td class='lc2'>
	<input type="text" size="40" name="ALTBE90" disabled title="外国（地区）企业有权签字人姓名备案前内容" maxlength='50' value=""> </td>
	<td class='lc2'><input type="text" size="40" name="ALTAF90" title="外国（地区）企业有权签字人姓名备案后内容" maxlength='50' > </td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="91" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>外国（地区）企业企业责任形式</td>
	<td class='lc2'>
 		<select name="ALTBE91" title="外国(地区)企业责任形式备案前内容" disabled style="width:192px; ">
			<option value="0">无</option><option value="1">有限责任形式</option><option value="2">无限责任形式</option>
      </select>
    </td>
	<td class='lc2'>
		<select name="ALTAF91" title="外国(地区)企业责任形式备案后内容" disblank style="width:192px; ">
			<option value="0">无</option><option value="1">有限责任形式</option><option value="2">无限责任形式</option>
		</select>
	</td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="92" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>外国（地区）企业资本（资产）</td>
	<td class='lc2'>
	<input type="text" size="20" name="ALTBE92" disabled title="外国（地区）企业资本（资产）备案前内容" maxlength='50' value="">万美元 </td>
	<td class='lc2'>
	<input type="text" size="20" name="ALTAF92" title="外国（地区）企业资本（资产）备案后内容" maxlength='50' >万美元 </td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="93" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>外国（地区）企业经营范围</td>
	<td class='lc2'>
	<textarea cols=40 rows=3 name="ALTBE93" disabled title="外国（地区）企业经营范围备案前内容" maxlength='500'></textarea> </td>
	<td class='lc2'>
	<textarea cols=40 rows=3 name="ALTAF93" title="外国（地区）企业经营范围备案后内容" maxlength='500' ></textarea> </td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="94" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>代表备案</td>
	<td class='lc2'colspan="2"><font color=red>代表备案请选择备案事项，保存后填写“代表信息”！</font>
	<input type="hidden" size="20" name="ALTBE94" disabled title="代表备案前内容" maxlength='50' >
	<input type="hidden" size="20" name="ALTAF94" title="代表备案后内容" maxlength='50' >
	</td>
</tr>
<!--  tr>
	<td class='lc1'><input name="ALTITEM" value="99" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>其他</td>
	<td class='lc2'>
	<input type="text" size="20" name="ALTBE99" disabled title="其他备案前内容" maxlength='50' > </td>
	<td class='lc2'><input type="text" size="20" name="ALTAF99" title="其他备案后内容" maxlength='50' > </td>
</tr -->


<tr>
	<td class='lc1'><input name="ALTITEM" value="790" type="checkbox" ></td>
	<td class='lc1'>财务负责人</td>
	<td class='lc2'colspan="2"><font color=red>请选择变更事项，保存后填写财务负责人信息！</font>
	<input type="hidden" name="ALTBE790"  maxlength='500'>
	<input type="hidden" name="ALTAF790"  maxlength='500'></td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="780" type="checkbox" ></td>
	<td class='lc1'>联络员</td>
	<td class='lc2'colspan="2"><font color=red>请选择变更事项，保存后填写联络员信息！</font>
	<input type="hidden" name="ALTBE780"  maxlength='500'>
	<input type="hidden" name="ALTAF780"  maxlength='500'></td>
</tr>
</table>