<table border="1" width="100%" >
<caption>外商投资合伙企业备案登记事项</caption>
<tr>
	<td class="yxsm" align="center" colspan="2">项目</td>
	<td class="yxsm" align="center">申请备案事项</td>
</tr>
<!--  tr>
	<td class='lc1'><input name="ALTITEM" value="10" type="checkbox" onclick="setvalue(this)" ></td>
	<td class='lc1'>合伙人</td>
	<td class='lc2'colspan="2"><font color=red>合伙人变更请选择变更事项，保存后填写“合伙情况”信息！</font>
	<input type="hidden" name="ALTBE10"  maxlength='500'>
	<input type="hidden" name="ALTAF10"  maxlength='500'></td> 
</tr -->
<tr>
	<td class='lc1'><input name="ALTITEM" value="73" type="checkbox" onclick="setvalue(this)"> </td>
	<td class='lc1'>合伙协议</td>
	<td class='lc2'>
	<input type="hidden" name="ALTBE73"  maxlength='500'>
	<textarea rows="3" cols="45" name="ALTAF73" title="合伙协议" maxlength='500' ></textarea></td>
</tr>

<!--tr>
	<td class='lc1'><input name="ALTITEM" value="74" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>合伙协议修正</td>
	<td class='lc2' >
	<input type="hidden" name="ALTBE74"  maxlength='500'>
	<textarea rows="3" cols="45" name="ALTAF74"  title="章程修正案" maxlength='500'></textarea></td>
</tr>
< tr>
	<td class='lc1'><input name="ALTITEM" value="62" type="checkbox" onclick="setvalue(this)" ></td>
	<td class='lc1'>工商联络员</td>
	<td class='lc2'colspan="2"><font color=red>工商联络员变更请选择变更事项，保存后填写“工商联络员”信息！</font>
	<input type="hidden" name="ALTBE62"  maxlength='500'>
	<input type="hidden" name="ALTAF62"  maxlength='500'></td> 
</tr -->
<tr>
	<td class='lc1'><input name="ALTITEM" value="63" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>外国合伙人法律文件送达接受人</td>
	<td class='lc2'><font style="color:red;">外国合伙人法律文件送达接受人事项,保存后填写“文件送达人”信息</font>
	<input type="hidden" name="ALTBE63" title="外国合伙人法律文件送达接受人备案前内容" maxlength='50'>
	<input type="hidden" size="40" name="ALTAF63" title="外国合伙人法律文件送达接受人备案后内容" maxlength='50'></td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="79" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>清算组成员</td>
	<td class='lc2'>
	<input type="hidden"  name="ALTBE79" title="清算组成员备案前内容" maxlength='50' >
	<input type="text" size="50" name="ALTAF79" title="清算组成员备案后内容" maxlength='200' > </td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="84" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>清算组负责人</td>
	<td class='lc2'>
	<input type="hidden" name="ALTBE84" title="清算组负责人备案前内容" maxlength='50'>
	<input type="text" size="50" name="ALTAF84" title="清算组负责人备案后内容" maxlength='50'></td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="87" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'>清算组负责人电话</td>
	<td class='lc2'>
	<input type="hidden" name="ALTBE87" title="清算组负责人电话备案前内容" maxlength='50'>
	<input type="text" size="50" name="ALTAF87" title="清算组负责人电话备案后内容" datatype=int maxlength='20'></td>
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="81" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'><%=title%>增加</td>
	<td class='lc2'><font color=red><%=title%>增加后请选择变更事项，保存后填写“<%=title%>”信息！</font>
	<input type="hidden" name="ALTBE81"  maxlength='500'>
	<input type="hidden" name="ALTAF81"  maxlength='500'></td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="83" type="checkbox" onclick="setvalue(this)"></td>
	<td class='lc1'><%=title%>注销</td>
	<td class='lc2'colspan="1"><font color=red><%=title%>注销后请选择变更事项，保存后填写“<%=title%>”信息！</font>
	<input type="hidden" name="ALTBE83"  maxlength='500'>
	<input type="hidden" name="ALTAF83"  maxlength='500'></td> 
</tr>
<tr>
	<td class='lc1'><input name="ALTITEM" value="790" type="checkbox" ></td>
	<td class='lc1'>财务负责人</td>
	<td class='lc2'colspan="2"><font color=red>请选择变更事项，保存后填写财务负责人信息！</font>
	<input type="hidden" name="ALTBE790"  maxlength='500'>
	<input type="hidden" name="ALTAF790"  maxlength='500'></td>
</tr>

<tr>
	<td class='lc1'><input name="ALTITEM" value="780" type="checkbox" ></td>
	<td class='lc1'>联络员</td>
	<td class='lc2'colspan="2"><font color=red>请选择变更事项，保存后填写联络员信息！</font>
	<input type="hidden" name="ALTBE780"  maxlength='500'>
	<input type="hidden" name="ALTAF780"  maxlength='500'></td>
</tr>
</table>