package com.business.remot.exterior.Authentication;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-07-07T15:28:09.913+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "AuthenticationRemotServiceService", 
                  wsdlLocation = "http://218.57.139.24:8082/authenticationService/services/AuthenticationService?wsdl",
                  targetNamespace = "http://service.exterior.remot.business.com/") 
public class AuthenticationRemotServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.exterior.remot.business.com/", "AuthenticationRemotServiceService");
    public final static QName AuthenticationRemotServicePort = new QName("http://service.exterior.remot.business.com/", "AuthenticationRemotServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://218.57.139.24:8082/authenticationService/services/AuthenticationService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthenticationRemotServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://218.57.139.24:8082/authenticationService/services/AuthenticationService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthenticationRemotServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthenticationRemotServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationRemotServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuthenticationRemotServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuthenticationRemotServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuthenticationRemotServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns AuthenticationRemotService
     */
    @WebEndpoint(name = "AuthenticationRemotServicePort")
    public AuthenticationRemotService getAuthenticationRemotServicePort() {
        return super.getPort(AuthenticationRemotServicePort, AuthenticationRemotService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationRemotService
     */
    @WebEndpoint(name = "AuthenticationRemotServicePort")
    public AuthenticationRemotService getAuthenticationRemotServicePort(WebServiceFeature... features) {
        return super.getPort(AuthenticationRemotServicePort, AuthenticationRemotService.class);
    }

}
