package com.business.remot.exterior.BusinessShow;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "BusinessShowService", targetNamespace = "http://service.exterior.remot.business.com/")
public interface BusinessShowService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "test", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.Test")
	@ResponseWrapper(localName = "testResponse", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.TestResponse")
	public String test(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "businessLicenceExQuery", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessLicenceExQuery")
	@ResponseWrapper(localName = "businessLicenceExQueryResponse", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessLicenceExQueryResponse")
	public String businessLicenceExQuery(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "businessFiling", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessFiling")
	@ResponseWrapper(localName = "businessFilingResponse", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessFilingResponse")
	public String businessFiling(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "businessCancelFiling", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessCancelFiling")
	@ResponseWrapper(localName = "businessCancelFilingResponse", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessCancelFilingResponse")
	public String businessCancelFiling(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "businessLicenceExSignQuery", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessLicenceExSignQuery")
	@ResponseWrapper(localName = "businessLicenceExSignQueryResponse", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessLicenceExSignQueryResponse")
	public String businessLicenceExSignQuery(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "businessFilingQuery", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessFilingQuery")
	@ResponseWrapper(localName = "businessFilingQueryResponse", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessFilingQueryResponse")
	public String businessFilingQuery(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "businessFilingEx", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessFilingEx")
	@ResponseWrapper(localName = "businessFilingExResponse", targetNamespace = "http://service.exterior.remot.business.com/", className = "com.business.remot.exterior.BusinessShow.BusinessFilingExResponse")
	public String businessFilingEx(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

}
