package com.business.remot.exterior.BusinessShow;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BusinessShowServiceService service = new BusinessShowServiceService();
 * BusinessShowService portType = service.getBusinessShowServicePort();
 * portType.test(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BusinessShowServiceService", targetNamespace = "http://service.exterior.remot.business.com/", wsdlLocation = "http://218.57.139.24:8083/businessShow/services/BusinessShowService?wsdl")
public class BusinessShowServiceService extends Service {

	private final static URL BUSINESSSHOWSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(BusinessShowServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = BusinessShowServiceService.class.getResource(".");
			url = new URL(baseUrl,
					"http://218.57.139.24:8083/businessShow/services/BusinessShowService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://218.57.139.24:8083/businessShow/services/BusinessShowService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BUSINESSSHOWSERVICESERVICE_WSDL_LOCATION = url;
	}

	public BusinessShowServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BusinessShowServiceService() {
		super(BUSINESSSHOWSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://service.exterior.remot.business.com/",
				"BusinessShowServiceService"));
	}
	public BusinessShowServiceService(URL wsdlLocation) {
		super(wsdlLocation, new QName(
				"http://service.exterior.remot.business.com/",
				"BusinessShowServiceService"));
	}
	/**
	 * 
	 * @return returns BusinessShowService
	 */
	@WebEndpoint(name = "BusinessShowServicePort")
	public BusinessShowService getBusinessShowServicePort() {
		return super.getPort(new QName(
				"http://service.exterior.remot.business.com/",
				"BusinessShowServicePort"), BusinessShowService.class);
	}

}
