<link rel="stylesheet" type="text/css" media="screen" href="<%=request.getContextPath() %>/support/jqueryUI/jquery-ui-1.9.2.custom.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<%=request.getContextPath() %>/support/jqugrid/ui.jqgrid.css" />
<script type="text/javascript" src="js/zhcc.js"></script>
<script type="text/javascript" src="../../support/jqgrid/grid.locale-cn.js"></script>
<script type="text/javascript" src="../../support/jqgrid/jquery.jqGrid.min.js"></script>